name: Docker Image Health Check

on:
  pull_request:
    branches:
      - master 

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for linux/amd64
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ github.sha }} \
          -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:latest \
          --load .

    - name: Test Docker Image on linux/amd64
      run: |
        echo "Testing Docker image on linux/amd64"
        docker run --platform linux/amd64 -d --name test-appium-device-farm-amd64 ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ github.sha }}
        sleep 10
        
        # Check if Appium server started successfully
        echo "Checking Appium server status"
        if ! docker exec test-appium-device-farm-amd64 curl --fail http://localhost:4723/wd/hub/status; then
          echo "Appium server did not start successfully."
          docker logs test-appium-device-farm-amd64
          docker stop test-appium-device-farm-amd64 || true
          docker rm test-appium-device-farm-amd64 || true
          exit 1
        fi
        echo "Appium server is running."

    - name: Clean up
      run: |
        docker stop test-appium-device-farm-amd64 || true
        docker rm test-appium-device-farm-amd64 || true