name: Docker Build and Run Check

on:
  pull_request:
    branches:
      - master 

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t appium-device-farm:${{ github.sha }} .  

    - name: Check if the Docker image runs
      run: |
        # Run the image and check if it's running
        docker run -d --name test-appium-device-farm appium-device-farm:${{ github.sha }}  # Run image in detached mode
        sleep 10  
        docker ps -a
        docker logs test-appium-device-farm

    - name: Clean up
      run: |
        docker stop test-appium-device-farm
        docker rm test-appium-device-farm