name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [docker-image-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Version from Dispatch Event
      if: github.event_name == 'repository_dispatch'
      run: |
        VERSION="${{ github.event.client_payload.version }}"
        BUILD_TOOLS_VERSION="${{ github.event.client_payload.build_tools_version }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV

    - name: Extract version from Dockerfile (if not set by dispatch)
      id: extract_version
      if: env.VERSION == ''
      run: |
        VERSION=$(grep -m 1 'LABEL APPIUM_VERSION' Dockerfile | cut -d '=' -f2 | tr -d '"')
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ENV APPIUM_VERSION' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ARG APPIUM_VERSION' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        if [ -z "$BUILD_TOOLS_VERSION" ]; then
          # Case 1: Independently triggered - Build images with version only
          docker build -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }} .
          docker build -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:latest .
        else
          # Case 2: Triggered by android-build-tools - Build images with version and build-tools version
          docker build -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }}-${{ env.BUILD_TOOLS_VERSION }} .
          docker build -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }} .
          docker build -t ${{ env.DOCKER_USERNAME }}/appium-device-farm:latest .
        fi

    - name: Push Docker images
      run: |
        if [ -z "$BUILD_TOOLS_VERSION" ]; then
          # Case 1: Independently triggered - Push images with version only
          docker push ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }}
        else
          # Case 2: Triggered by android-build-tools - Push images with version and build-tools version
          docker push ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }}-${{ env.BUILD_TOOLS_VERSION }}
          docker push ${{ env.DOCKER_USERNAME }}/appium-device-farm:${{ env.VERSION }}
        fi
        docker push ${{ env.DOCKER_USERNAME }}/appium-device-farm:latest

    - name: Clean up Docker images
      run: |
        docker image prune -af